### ISSUE TITLE
Apply or not apply a new track_id when lon data are correct?

### ISSUE THREAD

**Issue by treerink** [EC-Earth/cmor-fixer#2]
A choice has to be made whether a new `track_id` is provided to a file, when cmor-fixer is applied on a file which has correct data.

Actually I think it is better to keep a file untouched when the lon data are correct.

There are at least three reasons that the cmor-fixer script might be applied to files which have already correct lon data:

- Some new files with a newer and correct `ece2cmor3` version have been added
- NEMO data is falls within the CMIP6 directory, when using the cmor data root dir (to be sure one does not forget a table).
- The script is applied on a part of the data, and after something went wrong, it is applied again on all of it.

Other opinions?

**Comment by goord** [comment]
Hi @treerink I propose to not generate a new id if nothing is written. I can also somehow make the script return a list of files that have been modified (or write those in a file)

**Comment by etiennesky** [comment]
see #3 - files generated by LPJG do not have the problem, but the fixer will run for them because of the grid_label - not changing the lon values but changing other stuff.

**Comment by goord** [comment]
This can be tested in the modified_list branch. There I also fixed the creation date and added the option to write a file containing all modified files

**Comment by treerink** [comment]
Since  c3c02c54369e492fd775ee6e9a57adc36d8f4c4f we have the option  `--forceid` to always apply a new `tracking_id`.
