### ISSUE TITLE
Need to make cmor-fixer ignore symbolic links

### ISSUE THREAD

**Issue by pchengi** [EC-Earth/cmor-fixer#21]
# Issue
It's vital to get cmor-fixer to ignore symbolic links, as the ESGF publisher and tools such as esgdrs use symbolic links. Many production sites use esgdrs, which means that there might be symbolic links in the production directory structure. os.walk by default does not ignore symbolic links. Also, when you use the --npp option using more than one thread, this could lead to a dangerous race condition, with the cmor-fixer trying to open the same file using two different handles. 

# Suggested fix:
Check for and ignore if file is a symbolic link

**Comment by goord** [comment]
Fixed issue in 2b67f15851723295754a02aff4073324e4785033
