### ISSUE TITLE
apply fixer only on files generated by ifs, not those generated by LPJG

### ISSUE THREAD

**Issue by etiennesky** [EC-Earth/cmor-fixer#3]
It seems like the files generated by LPJG are ok

here is the lon var of an example file Lmon/fLitterSoil/gr/v20190726/fLitterSoil_Lmon_EC-Earth3-Veg_historical_r5i1p1f1_gr_185001-185012.nc

```
data:

 lon = 0, 0.703125, 1.40625, 2.109375, 2.8125, 3.515625, 4.21875, 4.921875, 
    5.625, 6.328125, 7.03125, 7.734375, 8.4375, 9.140625, 9.84375, 10.546875, 
    11.25, 11.953125, 12.65625, 13.359375, 14.0625, 14.765625, 15.46875, 
    16.171875, 16.875, 17.578125, 18.28125, 18.984375, 19.6875, 20.390625, 
    21.09375, 21.796875, 22.5, 23.203125, 23.90625, 24.609375, 25.3125, 
    26.015625, 26.71875, 27.421875, 28.125, 28.828125, 29.53125, 30.234375, 
...
```

But since the files generated by LPJG also have grid_label" == "gr" then they will be processed by this tool, which is not desirable. - especially if it shifts already correct data - is that the case?

But I am not sure how we can know from only the netcdf metadata in the file if LPJG was the generator.

**Comment by goord** [comment]
Hi Etienne, the script is written such that it doesn't apply a shift if the first longitude is 0, which is the case above. I will make sure the tracking_id is not changed if the file doesn't get modified at all (see issue #2 )

**Comment by etiennesky** [comment]
ok thanks, that test comes from the if offset > 0.: test 

I will test the fixer once #3 is solved, thanks!
